### ISSUE TITLE
venv requirement issue

### ISSUE THREAD

**Issue by r3dSh4d0w** [bourinus/Fall#3]
requirements are not correctly installed in venv
(venv) root@debianShadow:/home/sh4d0w/eclipse-workspace/Fall# pip list
Package    Version
---------- -------
pip        20.1.1
setuptools 47.1.1
wheel      0.34.2

**Comment by bourinus** [comment]
C'est bien lie au sujet ?? la doc ne compile pas.

make[1]: Entering directory '/home/billy/Desktop/Fall/docs'
Running Sphinx v1.8.4

Extension error:
Could not import extension sphinx.ext.mathbasesphinx.ext.githubpages (exception: No module named 'sphinx.ext.mathbasesphinx')

**Comment by bourinus** [comment]
[bashrc.txt](https://github.com/bourinus/Fall/files/4798841/bashrc.txt)
[bash_aliases.txt](https://github.com/bourinus/Fall/files/4798842/bash_aliases.txt)

**Comment by bourinus** [comment]
https://stackoverflow.com/questions/50199070/sphinx-extension-installation-of-sphinxcontrib-bibtex

**Comment by r3dSh4d0w** [comment]
Venv builded with depedencies
